// gameLogic.js - Game logic and constants

export const MOTIVES = [
  'Protecting Flora',
  'Avenging Mrs. Ferris\' Death',
  'Thrown out of Will',
  'Covering up Money Embezzlement',
  'Covering up the blackmail',
  'Monetary benefit from Erik\'s Death',
  'AI Fraud'
];

export const CORRECT_SOLUTION = {
  murderer: 'cecilia',
  motive: 'Covering up the blackmail'
};

export const FEEDBACK_MESSAGES = {
  incorrect: {
    message: "How can you be so wrong Watson?! No no no….you need to be cautious about distinguishing facts within those AI summaries. Make sure to come back to me only with your highlights completed next time",
    requiresHighlighting: true
  },
  partialCorrectMurderer: {
    message: "Dr. Sheppard does look suspicious. But, this motive does not make sense. You need to get to the bottom of it. Keep Digging, Do your little highlighting thing if you want to.",
    requiresHighlighting: true
  },
  partialCorrectMotive: {
    message: "That does sound like a plausible motive. But, I don't think it's associated to this person. Remember you need to be cautious about distinguishing facts within those AI summaries. Come back to me with your highlights in the AI summaries so we can look together.",
    requiresHighlighting: true
  },
  correct: {
    message: "Let's go! Looks like you did learn a thing or two from me to solve this case all by yourself! Make sure to pat yourself on the back–not only for solving this case but also for learning about biases within AI models and how they might surface. AI systems are trained or large datasets which might bring with them historical biases. While the current state AI models perform well with interpreting and synthesizing factual information, insufficient or biased training data can lead to the models making incorrect assumptions or generalizing inappropriately. This also leads the AI models to hallucinate, or generate inaccurate information. I recognize that the presence of AI helps us save time and increase our work efficiency but it's also important that you verify the information generated by AI with multiple sources.",
    requiresHighlighting: false
  }
};

export const checkSolution = (suspectId, selectedMotive) => {
  if (suspectId === CORRECT_SOLUTION.murderer && selectedMotive === CORRECT_SOLUTION.motive) {
    return 'correct';
  } else if (suspectId === CORRECT_SOLUTION.murderer) {
    return 'partialCorrectMurderer';
  } else if (selectedMotive === CORRECT_SOLUTION.motive) {
    return 'partialCorrectMotive';
  }
  return 'incorrect';
};
